import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import "./globals.css";
import { Inter, Source_Sans_3 } from "next/font/google";
import "./globals.css";

// const roboto = Roboto({ subsets: ["latin"], weight: "300" });
const source = Source_Sans_3({ subsets: ["latin"], weight: "400" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={source.className}>{children}</body>
    </html>
  );
}
